### ISSUE TITLE
Error Loading pyBRAT Project For Ally

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRAVEPlugin#43] opened 2021-08-24 18:13 UTC
@leallysmith is experiencing a similar error to #41 when she tries to load a pyBRAT project curated by @Cashe93. Here's the error message:

![image](https://user-images.githubusercontent.com/8645379/130667579-640bbb62-7403-48b4-93f3-e2380f5a0940.png)

Here is Ally's system:

- QRAVE 3.52
- QGIS 3.20.2
- [pyBRAT project](https://usu.box.com/s/lstcgo1czzaccpcfpeax1ta6sj594mp2)
- She is using the [pyBRAT business logic that was recently re-based onto master](https://github.com/Riverscapes/RiverscapesXML/blob/e0b4805fd7f9d659b61dd110c3a60c10013f7529/RaveBusinessLogic/pyBRAT.xml).

Other Information:

- This same project and BL works for @Cashe93 using QGIS 3.20.2
- This same project and BL work for me using QGIS 3.16.10

**Comment by MattReimer** [comment] 2021-08-24 19:04
Definitely a legitimate error with QRave that needs fixing

**Comment by philipbaileynar** [comment] 2021-08-24 19:37
Additonal info... @leallysmith  is using a computer that others in the lab were using before she started (i.e. could be dirty system with other lingering files)

**Comment by philipbaileynar** [comment] 2021-08-24 19:56
I had Ally email me her pBRAT.xml business logic from here QRAVE resources folder.


I saved this file into my local copy of the RiverscapesXML master branch. git showed no differences, proving that her QRAVE resource folder contains the same version as GitHub master branch.

**Comment by joewheaton** [comment] 2021-08-24 21:28
Not that it helps, but I just downloaded project on my QGIS (QGIS version: 3.20.0-Odense), RAVE 0.5.2 and updated recourses and confirmed I have latest `pyBRAT.xml` business logic. It [worked for me](https://youtu.be/uijwPxwksxY), see:
[![You Tube Video](http://img.youtube.com/vi/uijwPxwksxY/0.jpg)](https://youtu.be/uijwPxwksxY)

@leallysmith it might be helpful for testing this if you recorded a little video of exactly what you are experiencing and posted it.

For instructions on recording videos with Faststone and posting them to YouTube, see: 
For instructions on how to embed videos in MarkDown posts like this, see: http://etal.joewheaton.org/faststone-capture.htmlhttps://gist.github.com/joewheaton/002acd9ea725f6d4a1bac38ee9a0dd50#embed-a-video

**Comment by leallysmith** [comment] 2021-08-25 14:10
I think I embedded the video? The tutorial links lead to 404 pages. I also pasted in the youtube link itself in case my embed failed. [Link](https://youtu.be/ZD3pVowMZjk)
[![Alt text](https://img.youtube.com/vi/ZD3pVowMZjk/0.jpg)](https://www.youtube.com/watch?v=ZD3pVowMZjk)

**Comment by MattReimer** [comment] 2021-08-25 15:25
@leallysmith that's excellent. Thanks for doing that. Should really help us quickly zone in on the problem

**Comment by MattReimer** [comment] 2021-08-31 23:29
Ok. I've reviewed all the videos and evidence provided (big thanks @leallysmith and @joewheaton for the great vidoes) and I think I've got it covered. I'll be putting out a patch release 0.6.0 tomorrow morning and I'll let you know when you can get it and try.

Given the attention to business logic developers I've really tried to give better errors whenever possible but I'll ellaborate on that in my changelog patch notes at release time.

**Comment by Cashe93** [comment] 2021-09-03 20:00
@MattReimer, any word on the patch release?

**Comment by MattReimer** [comment] 2021-09-03 20:04
I'm typing up the release notes now. End of day at the latest.

**Comment by Cashe93** [comment] 2021-09-03 20:06
Awesome, thanks!

**Comment by MattReimer** [comment] 2021-09-06 04:58
I'm closing this with the release (which is out but yet to be approved by OSGEO). I'll reopen this issue if it isn't fixed.

**Closed by MattReimer** 2021-09-06 04:58 UTC
Labels: :fire: BLOCKED

**Comment by MattReimer** [comment] 2021-09-07 17:27
@leallysmith and @Cashe93 0.6.0 is out (apparently my anouncement message didn't notify people. Sorry)

Please upgrade using the QGIS `Plugins --> Manage and install plugins...` menu. 

FYI this patch took a while because of a backlog of other unrelated issues. If this issue still exists get in touch ASAP and the next one will be MUCH faster.

**Comment by leallysmith** [comment] 2021-09-07 20:50
Thanks @MattReimer ! Now I've got an issue popping up where some projects open fine and others just give me a generic error that I've put in below. Some of the projects that won't open on my end have run fine on Cashe's system previously.
![QRAVEerror](https://user-images.githubusercontent.com/89225401/132407317-fef7490a-02dd-4f67-8eb7-0437fc18ce12.PNG)
Could you direct me to where I find the QRAVE logs so I can find the problem and resolve it myself or if I can't, I can provide you with more detail about what is actually occurring.

**Comment by MattReimer** [comment] 2021-09-07 21:07
Hey @leallysmith this is all good. I've changed the way we look for and handle errors to be a little more strict, a little more helpful and a lot more consistent.

Also if you can copy and paste the error text directly into github issues that helps us developers out quite a bit.

### Getting to logs

First open the log messages panel. I like to get to it from the toolbar right-click menu:

<img width="662" alt="Screen Shot 2021-09-07 at 1 56 36 PM" src="https://user-images.githubusercontent.com/1063391/132410967-a05df5d3-6451-4df0-acfe-bd3a9249d30e.png">

Then look for the QRave tab

<img width="887" alt="Screen Shot 2021-09-07 at 1 58 24 PM" src="https://user-images.githubusercontent.com/1063391/132411004-71b83228-9cfd-4e60-9730-c836adae282a.png">
